### ISSUE TITLE
codec can't decode byte

### ISSUE THREAD

**Issue by Arthurfogo7** [ffreemt/deepl-tr-pyppeteer#1]
When I try to run the script this error appears on the screen.
[E 210917 13:02:47 load_text:60]  Reading script.txt exc: 'utf-8' codec can't decode byte 0xff in position 3399835: invalid start byte
(The text is in japanese)

**Comment by yucongo** [comment]
Your file is probably not in utf-8 format. I'll patch  load_text in the next version. In the meantime, try to save your file in utf-8 format and give it another try.

**Comment by Arthurfogo7** [comment]
So I converted to UTF8 and this happened:
 | 0/2 [00:00<?, ?it/s][E 210918 09:21:43 deepl_tr_pp:294]  # of original paras (188) not match # of translated paras (187)
[E 210918 09:21:43 deepl_tr_pp:295]  something weird may have occurred.
[E 210918 09:21:43 deepl_tr_pp:296]  But we proceed nevertheless.
 50%|██████████████████████████████████████████                                          | 1/2 [00:30<00:30, 30.59s/it][E 210918 09:21:58 deepl_tr_pp:294]  # of original paras (45) not match # of translated paras (46)
[E 210918 09:21:58 deepl_tr_pp:295]  something weird may have occurred.
[E 210918 09:21:58 deepl_tr_pp:296]  But we proceed nevertheless.

**Comment by ffreemt** [comment]
`deepl_tr_pp` tries to translate one-to-one for each paragraph. But sometimes, it's unable to do that. Hence the result will be misaligned paragraphs. Those messages warn you about the misalignment.

There are probably unusual characters in the original text. For example `/`, `#` etc, (`/` is already processed by `deepl_tr_pp`). Try to replace those characters before sending to `deepl_tr_pp`. For example, replace `#` with a space, do `"...".replace("#", " ")`

You can take a look at the resultant `..._tr.docx` file and look for where the misalignment starts.

If it's feasible, attache the file and I'll take a look.
